language: node_js
node_js:
  - "10"
before_install:
  - npm install -r
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    fi
script:
  - npm run lint || (touch failed && false)
  - npm run all-test || (touch failed && false)
  - docker build -t gomezguillaume/browser-ui-test . || (touch failed && false)
  - docker run -v "$PWD:/data" gomezguillaume/browser-ui-test --test-folder /data/tests/scripts/ --failure-folder /data/failures --variable DOC_PATH /data/tests/html_files || (touch failed && false)
  - if [ ! -f failed ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push gomezguillaume/browser-ui-test && echo "pushed!";
    else
      echo "not pushed!";
    fi
