language: node_js
node_js:
  - "10"
before_install:
  - npm install -r
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    fi
script:
  - npm run lint
  - npm run all-test
  - docker build --label "org.label-schema.vcs-ref=$TRAVIS_COMMIT" -t gomezguillaume/browser-ui-test .
  - docker run -v "$PWD:/data" gomezguillaume/browser-ui-test --test-folder tests/scripts/ --failure-folder failures --variable DOC_PATH tests/html_files
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push gomezguillaume/browser-ui-test && echo "pushed!";
    else
      echo "not pushed!";
    fi