on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install -r
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run all-test
      - name: Build docker image
        run: docker build -t gomezguillaume/browser-ui-test .
      - name: Run GUI tests
        run: docker run -v "$PWD:/data" gomezguillaume/browser-ui-test --test-folder /data/tests/scripts/ --failure-folder /data/failures --variable DOC_PATH /data/tests/html_files
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build docker image with date
        run: docker build -t gomezguillaume/browser-ui-test:`date '+%Y-%m-%d'` .
      - name: Publish new versions
        run: |
          docker push gomezguillaume/browser-ui-test
          docker push gomezguillaume/browser-ui-test:`date '+%Y-%m-%d'`
